/*
  WARNING: DO NOT EDIT THIS FILE
  This file is generated programatically by golden_test_generator.rb
*/
#[test]
fn linear_search() {
  super::test_golden_bytecode("./src/codegen/tests/golden/linear_search.golden")
}
