/*
  WARNING: DO NOT EDIT THIS FILE
  This file is generated programatically by golden_test_generator.rb
*/
#[test]
fn lowering_no_input() {
  super::test_golden_ir("./src/ir/tests/golden/lowering_no_input.golden")
}
