
/*
  WARNING: DO NOT EDIT THIS FILE
  This file is generated programatically by scripts/fixture_test_generator.rb
*/

#[test]
fn multi_val_closure() {
  super::fixture_test("multi_val_closure")
}

#[test]
fn basic_popping() {
  super::fixture_test("basic_popping")
}

#[test]
fn powers_of_two() {
  super::fixture_test("powers_of_two")
}

#[test]
fn farenheit_to_celsius() {
  super::fixture_test("farenheit_to_celsius")
}

#[test]
fn rotate_array() {
  super::fixture_test("rotate_array")
}

#[test]
fn binding() {
  super::fixture_test("binding")
}

#[test]
fn switch_print() {
  super::fixture_test("switch_print")
}

#[test]
fn calling_non_func() {
  super::fixture_test("calling_non_func")
}

#[test]
fn globals() {
  super::fixture_test("globals")
}

#[test]
fn basic_map_usage() {
  super::fixture_test("basic_map_usage")
}

#[test]
fn access_list_via_float() {
  super::fixture_test("access_list_via_float")
}

#[test]
fn eratosthenes_sieve() {
  super::fixture_test("eratosthenes_sieve")
}

#[test]
fn closure_counter() {
  super::fixture_test("closure_counter")
}

#[test]
fn dead_code() {
  super::fixture_test("dead_code")
}

#[test]
fn fibonacci() {
  super::fixture_test("fibonacci")
}

#[test]
fn hello_world() {
  super::fixture_test("hello_world")
}

#[test]
fn big_backtrace() {
  super::fixture_test("big_backtrace")
}

#[test]
fn basic_delete_usage() {
  super::fixture_test("basic_delete_usage")
}

#[test]
fn one_plus_one() {
  super::fixture_test("one_plus_one")
}

#[test]
fn linear_search() {
  super::fixture_test("linear_search")
}

#[test]
fn constant_folding() {
  super::fixture_test("constant_folding")
}

#[test]
fn lucky_number() {
  super::fixture_test("lucky_number")
}

#[test]
fn euclidean_gcd() {
  super::fixture_test("euclidean_gcd")
}

#[test]
fn parsing_error() {
  super::fixture_test("parsing_error")
}

#[test]
fn if_else() {
  super::fixture_test("if_else")
}

#[test]
fn basic_pushing() {
  super::fixture_test("basic_pushing")
}
