
/*
  WARNING: DO NOT EDIT THIS FILE
  This file is generated programatically by scripts/fixture_test_generator.rb
*/

#[test]
fn powers_of_two() {
  super::fixture_test("powers_of_two")
}

#[test]
fn farenheit_to_celsius() {
  super::fixture_test("farenheit_to_celsius")
}

#[test]
fn rotate_array() {
  super::fixture_test("rotate_array")
}

#[test]
fn binding() {
  super::fixture_test("binding")
}

#[test]
fn switch_print() {
  super::fixture_test("switch_print")
}

#[test]
fn access_list_via_float() {
  super::fixture_test("access_list_via_float")
}

#[test]
fn closure_counter() {
  super::fixture_test("closure_counter")
}

#[test]
fn dead_code() {
  super::fixture_test("dead_code")
}

#[test]
fn hello_world() {
  super::fixture_test("hello_world")
}

#[test]
fn linear_search() {
  super::fixture_test("linear_search")
}

#[test]
fn constant_folding() {
  super::fixture_test("constant_folding")
}

#[test]
fn lucky_number() {
  super::fixture_test("lucky_number")
}

#[test]
fn if_else() {
  super::fixture_test("if_else")
}
