
/*
  WARNING: DO NOT EDIT THIS FILE
  This file is generated programatically by scripts/fixture_test_generator.rb
*/

#[test]
fn clone_intrinsic() {
  super::fixture_test("clone_intrinsic")
}

#[test]
fn arity_intrinsic() {
  super::fixture_test("arity_intrinsic")
}

#[test]
fn int_intrinsic() {
  super::fixture_test("int_intrinsic")
}

#[test]
fn multi_val_closure() {
  super::fixture_test("multi_val_closure")
}

#[test]
fn basic_popping() {
  super::fixture_test("basic_popping")
}

#[test]
fn fizzbuzz() {
  super::fixture_test("fizzbuzz")
}

#[test]
fn powers_of_two() {
  super::fixture_test("powers_of_two")
}

#[test]
fn farenheit_to_celsius() {
  super::fixture_test("farenheit_to_celsius")
}

#[test]
fn push_operator() {
  super::fixture_test("push_operator")
}

#[test]
fn expr_precedence() {
  super::fixture_test("expr_precedence")
}

#[test]
fn rotate_array() {
  super::fixture_test("rotate_array")
}

#[test]
fn math_ops() {
  super::fixture_test("math_ops")
}

#[test]
fn binding() {
  super::fixture_test("binding")
}

#[test]
fn call_non_intrinsic_sym() {
  super::fixture_test("call_non_intrinsic_sym")
}

#[test]
fn switch_print() {
  super::fixture_test("switch_print")
}

#[test]
fn calling_non_func() {
  super::fixture_test("calling_non_func")
}

#[test]
fn null_intrinsic() {
  super::fixture_test("null_intrinsic")
}

#[test]
fn globals() {
  super::fixture_test("globals")
}

#[test]
fn basic_map_usage() {
  super::fixture_test("basic_map_usage")
}

#[test]
fn recursive() {
  super::fixture_test("recursive")
}

#[test]
fn call_with_wrong_num_args() {
  super::fixture_test("call_with_wrong_num_args")
}

#[test]
fn very_large_map() {
  super::fixture_test("very_large_map")
}

#[test]
fn access_list_via_float() {
  super::fixture_test("access_list_via_float")
}

#[test]
fn float_intrinsic() {
  super::fixture_test("float_intrinsic")
}

#[test]
fn map_with_lists_as_keys() {
  super::fixture_test("map_with_lists_as_keys")
}

#[test]
fn str_intrinsic() {
  super::fixture_test("str_intrinsic")
}

#[test]
fn eratosthenes_sieve() {
  super::fixture_test("eratosthenes_sieve")
}

#[test]
fn closure_counter() {
  super::fixture_test("closure_counter")
}

#[test]
fn dead_code() {
  super::fixture_test("dead_code")
}

#[test]
fn fibonacci() {
  super::fixture_test("fibonacci")
}

#[test]
fn type_intrinsic() {
  super::fixture_test("type_intrinsic")
}

#[test]
fn hello_world() {
  super::fixture_test("hello_world")
}

#[test]
fn exporting() {
  super::fixture_test("exporting")
}

#[test]
fn inserting_and_deleting_on_map() {
  super::fixture_test("inserting_and_deleting_on_map")
}

#[test]
fn importing() {
  super::fixture_test("importing")
}

#[test]
fn big_backtrace() {
  super::fixture_test("big_backtrace")
}

#[test]
fn not_op() {
  super::fixture_test("not_op")
}

#[test]
fn basic_delete_usage() {
  super::fixture_test("basic_delete_usage")
}

#[test]
fn one_plus_one() {
  super::fixture_test("one_plus_one")
}

#[test]
fn bind_intrinsic() {
  super::fixture_test("bind_intrinsic")
}

#[test]
fn linear_search() {
  super::fixture_test("linear_search")
}

#[test]
fn constant_folding() {
  super::fixture_test("constant_folding")
}

#[test]
fn string_indexing() {
  super::fixture_test("string_indexing")
}

#[test]
fn lucky_number() {
  super::fixture_test("lucky_number")
}

#[test]
fn divide_by_zero() {
  super::fixture_test("divide_by_zero")
}

#[test]
fn bool_intrinsic() {
  super::fixture_test("bool_intrinsic")
}

#[test]
fn bad_import() {
  super::fixture_test("bad_import")
}

#[test]
fn euclidean_gcd() {
  super::fixture_test("euclidean_gcd")
}

#[test]
fn parsing_error() {
  super::fixture_test("parsing_error")
}

#[test]
fn sym_intrinsic() {
  super::fixture_test("sym_intrinsic")
}

#[test]
fn if_else() {
  super::fixture_test("if_else")
}

#[test]
fn basic_pushing() {
  super::fixture_test("basic_pushing")
}
