/*
  WARNING: DO NOT EDIT THIS FILE
  This file is generated programatically by golden_test_generator.rb
*/
#[test]
fn bool_intrinsic_fn() {
  super::test_golden_output("./src/runtime/tests/golden/bool_intrinsic_fn.golden")
}

#[test]
fn str_intrinsic() {
  super::test_golden_output("./src/runtime/tests/golden/str_intrinsic.golden")
}

#[test]
fn multiplication() {
  super::test_golden_output("./src/runtime/tests/golden/multiplication.golden")
}

#[test]
fn clone_intrinsic_fn() {
  super::test_golden_output("./src/runtime/tests/golden/clone_intrinsic_fn.golden")
}

#[test]
fn type_intrinsic_fn() {
  super::test_golden_output("./src/runtime/tests/golden/type_intrinsic_fn.golden")
}

#[test]
fn arity_intrinsic() {
  super::test_golden_output("./src/runtime/tests/golden/arity_intrinsic.golden")
}

#[test]
fn subtraction() {
  super::test_golden_output("./src/runtime/tests/golden/subtraction.golden")
}

#[test]
fn two_sum() {
  super::test_golden_output("./src/runtime/tests/golden/two_sum.golden")
}

#[test]
fn num_intrinsic() {
  super::test_golden_output("./src/runtime/tests/golden/num_intrinsic.golden")
}

#[test]
fn division() {
  super::test_golden_output("./src/runtime/tests/golden/division.golden")
}

#[test]
fn comparisons() {
  super::test_golden_output("./src/runtime/tests/golden/comparisons.golden")
}

#[test]
fn addition() {
  super::test_golden_output("./src/runtime/tests/golden/addition.golden")
}

#[test]
fn import() {
  super::test_golden_output("./src/runtime/tests/golden/import.golden")
}

#[test]
fn bind_intrinsic_fn() {
  super::test_golden_output("./src/runtime/tests/golden/bind_intrinsic_fn.golden")
}

#[test]
fn math_intrinsics() {
  super::test_golden_output("./src/runtime/tests/golden/math_intrinsics.golden")
}

#[test]
fn symbol_comparison_test() {
  super::test_golden_output("./src/runtime/tests/golden/symbol_comparison_test.golden")
}

#[test]
fn read_chars_from_string() {
  super::test_golden_output("./src/runtime/tests/golden/read_chars_from_string.golden")
}
