/*
  WARNING: DO NOT EDIT THIS FILE
  This file is generated programatically by golden_test_generator.rb
*/
#[test]
fn one_plus_one() {
  super::test_golden_output("./src/runtime/tests/golden/one_plus_one.golden")
}

#[test]
fn globals_test() {
  super::test_golden_output("./src/runtime/tests/golden/globals_test.golden")
}

#[test]
fn closure_printing() {
  super::test_golden_output("./src/runtime/tests/golden/closure_printing.golden")
}

#[test]
fn euclidean_gcd() {
  super::test_golden_output("./src/runtime/tests/golden/euclidean_gcd.golden")
}
